In [ ]:
# Numpy is Highly Optimised and use low level code in backend (c program)
# it stores data in contagious memory block making acces faster then list 
# why we use Numpy -> to overcome slowness of List 

# Efficient Array Handling: NumPy arrays are more efficient in terms of memory and performance compared to 
# standard Python lists. They allow you to store large amounts of data and perform computations efficiently.

# # Vectorized Operations: NumPy supports vectorized operations, which means you can perform element-wise operations
#     on arrays without using explicit loops. This makes code shorter and faster.

# # Mathematical Functions: It provides a wide range of mathematical functions like linear algebra, statistical 
# functions, and random number generation.

# # Interoperability: NumPy arrays can be used with other libraries like Pandas, SciPy, and Matplotlib. 
#     It is also a foundation for many other Python libraries used in data science and machine learning.

# # Multidimensional Arrays: NumPy allows you to create and manipulate multi-dimensional arrays 
# (e.g., matrices, tensors), which is essential in fields like image processing, machine learning, and scientific computing.

# # Broadcasting: NumPy supports broadcasting, which is a way to apply binary operations (like addition, subtraction) 
# on arrays of different shapes without explicit looping.

# # Compatibility: It integrates seamlessly with C, C++, and Fortran libraries, allowing you to leverage 
# high-performance computing.



In [63]:
import numpy as np
import time 

# Python list for calculation of speed 
# size = 1_000000
list1 = [10000000000]
list2 = [10000000000]
start = time.time()
result = [x * y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)
print(result)

Python list addition time: 0.0002741813659667969
[100000000000000000000]


In [67]:

# Numpy Array
list1 = [100000000]
list2 = [100000000]

array1=np.array(list1)
array2=np.array(list2)

start=time.time()
result = [x * y for x, y in zip(list1, list2)]
stop=time.time()
print(result)
print(stop - start)

[10000000000000000]
0.0


In [77]:
# Zip will merge 2 List
l1=[1,2,3,4]
l2=[5,6,4,8]
result= [x*y for x,y in zip(l1,l2)]
print(result)

[5, 12, 12, 32]


In [93]:
# Creating numpy array 

arr1=np.array([1,2,3,4])
print(arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

print(type(arr1))
print(arr2.shape)


[1 2 3 4]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
# Memory Efficiency – NumPy vs. Lists
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) )
print("NumPy array size:", numpy_data.nbytes)

In [130]:
# Vectorization – No More Loops!
# NumPy avoids loops by applying operations to entire arrays at once using 
# SIMD (Single Instruction, Multiple Data) and other low-level optimizations. 
# SIMD is a CPU-level optimization provided by modern processors.

# Python list (loop-based)
list1=[1,2,3,4]
list_square=[x**2 for x in list1]
print(list_square)

# NumPy (vectorized) NumPy avoids loops by applying operations to entire arrays at once using SIMD
# (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level 
# optimization provided by modern processors.
arr1 = np.array([1, 2, 3, 4, 5])
list_Square=arr1**2
print(list_Square)

[1, 4, 9, 16]
[ 1  4  9 16 25]


In [138]:
# Q1 Create a NumPy array with values from 10 to 100 and print its shape.
arry1=np.array(range(10,100))
print(arry1.shape)

(90,)


In [163]:
#Q2 Find the memory size of a NumPy array with 1 million elements

import sys
import numpy as np

arr3 =np.array(range(1000000))
print(arr3.nbytes)  # # Get the memory size in bytes

4000000
