In [5]:
#Creating NumPy Arrays
import numpy as np

arr1=np.array([1,2,3,4]) # 1 D array
arr2=np.array([[1,2,3,4],[1,2,3,4]]) # 2 D array

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [9]:
#Creating Arrays from Scratch:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [19]:
np.eye(4) #  eigen matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.arange(1, 10, 2) # add eliments till range 

array([1, 3, 5, 7, 9])

In [28]:
#Checking Array Properties

arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int32


In [30]:
# Changing Data Types
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32
 
arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


In [32]:
# Reshaping and Flattening Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
