In [18]:
# Indexing and slicing 
#Slicing returns a view, not a copy! Changes affect the original array


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110   0]
 [ 10  20  30  40]]


In [ ]:

import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,0],[10,20,30,40]])
print(arr)

In [24]:
array=arr.flatten()
print(array)
print(array[:5]) # before 5
print(array[5:]) # After 5
print(array[6:10]) # between 6-10
print(array[::2]) # gap of 2



[ 10  20  30  40  50  60  70  80  90 100 110   0  10  20  30  40]
[10 20 30 40 50]
[ 60  70  80  90 100 110   0  10  20  30  40]
[ 70  80  90 100]
[ 10  30  50  70  90 110  10  30]


In [46]:
#Slicing returns a view, not a copy! Changes affect the original array
array=np.array([ 10 , 20 , 30  ,40  ,50 , 60 , 70,  80  ,90 ,100 ])
newarr=array[2:5]
newarr[1]=100000
print(array)


[    10     20     30 100000     50     60     70     80     90    100]


In [56]:
# fancy indexing 
ar=np.array([1,2,3,4])
indx=[0,3] # passing index value 
print(ar[indx])

[1 4]


In [ ]:
# boolean masking
ar=np.array([1,2,3,4])
mask=ar >2
print
