In [1]:
# Create a NumPy array of integers from 10 to 50
import numpy as np
arr=np.array(range(10,50))
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [23]:
# Create a 3x3 matrix with values ranging from 1 to 9.
array=np.arange(1,10).reshape(3,3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# Create a 5x5 matrix filled with zeros.
arrays=np.zeros((5,5))
print(arrays)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [39]:
# identity matrics
array=np.eye(4)
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
# Random number between 0 and 1
arr=np.random.rand()
print(arr)

0.458261223563712


In [65]:
# 6. 10 random integers between 1 and 100
a6 = np.random.randint(1, 101, size=10)
print(a6)

[92 33 12 67 59  8 75  4  3  4]


In [75]:
# 7. Max, Min, Mean of array
print("Min",np.min(a6))
print("Max",np.max(a6))
print("mean",np.mean(a6))
print("median",np.median(a6))

Min 3
Max 92
mean 35.7
median 22.5


In [93]:
# 8. Replace odd numbers with -1
a8 = np.array([92, 33, 12, 67, 59,  8, 75,  4,  3,  4])
a8[a8 % 2 == 1] = -1
print(a8)

[92 -1 12 -1 -1  8 -1  4 -1  4]


In [113]:
# 9. Reshape 1D array to 3x4
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [123]:
# 10. Even numbers between 1 and 20

e=np.arange(2,21,2)
print(e
     )

[ 2  4  6  8 10 12 14 16 18 20]


In [127]:
# 11. 3x3 matrix with middle element 99
a11 = np.ones((3, 3))
a11[1,1]=99
print(a11)

[[ 1.  1.  1.]
 [ 1. 99.  1.]
 [ 1.  1.  1.]]


In [139]:
#Reverse a 1D array
arr=np.array([1,2,3,4,5,6,7,7,89,9])
print(arr[::-1])

[ 9 89  7  7  6  5  4  3  2  1]


In [143]:
# 13. Stack arrays vertically and horizontally
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Vertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]


In [145]:
# 15. Square root of each element
a15 = np.array([1, 4, 9, 16])
print(np.sqrt(a15))


[1. 2. 3. 4.]


In [147]:
#Replace elements > 50 with 50
a16 = np.array([45, 60, 30, 70])
a16[a16 > 50] = 50
print(a16)

[45 50 30 50]


In [149]:
# 18. Row and column sums
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Row sums:", a.sum(axis=1))
print("Column sums:", a.sum(axis=0))


Row sums: [ 6 15]
Column sums: [5 7 9]


In [153]:
a = np.array([1, 2, 3])
b = np.array([1, 5, 6])
a==b

array([ True, False, False])